### ISSUE TITLE
Issues installing Xacc on Ubuntu

### ISSUE THREAD

**Issue by joehellmers** [eclipse/xacc#177]
When trying to install cmake using pip
`sudo -H python3 -m pip install cmake`
I get the message
`ModuleNotFoundError: No module named 'skbuild'`
Am I supposed to install skbuild as well?  If so, what's the best way to do that?

**Comment by amccaskey** [comment]
I've run across this, here's what fixed it for me
```
python3 -m pip install --upgrade pip
```

**Comment by hellmersjl3ds** [comment]
Thanks that gets me most of the way there.

In order to get an example to work I needed to install qiskit.
When I tried to install the tnqvm simulator I had to use sudo.

Are there other python packages I need to install?  For Rigetti or D-Wave for example?

**Comment by amccaskey** [comment]
In order to run any python examples that leverage the `aer` Accelerator, you'll have to install qiskit. 

By default, XACC should install to $HOME/.xacc, so should be no need to use sudo for further plugin installs like TNQVM. If you did, make sure that XACC is installing to $HOME/.xacc and that the permissions didn't get messed up for some reason. 

We do have a D-Wave Accelerator implementation that delegates to D-Wave Ocean SDK. So if you'd like to use that then you'll also have to pip install dwave-ocean-sdk. You don't have to though, we have a D-Wave Accelerator that makes direct REST calls to the D-Wave QPU server (if you have access to it)

**Comment by joehellmers** [comment]
Thanks.
