### ISSUE TITLE
Mlpack optimiser not working with QAOA algorithm

### ISSUE THREAD

**Issue by aswanthkrishna** [eclipse/xacc#209]
I am trying to run the qaoa algorithm with the 'mlpack' optimizer. The cost function is not getting optimized. NLopt is working fine though. 

![mlpck](https://user-images.githubusercontent.com/53708665/84947080-447ab000-b107-11ea-99fb-a144f966ca88.png)

How to fix this? 
Thank you!

**Comment by amccaskey** [comment]
Can you post the code snippet ( or is it just the python qaoa_example.py with the optimizer string set to mlpack?)?

Most of the mlpack backend solvers require OptFunctions that produce gradients. By default the qaoa algorithm will use vqe without gradients. We have new support as of a couple of days ago to turn gradients for vqe, but have not tried it out for qaoa. My guess for your issue is that mlpack is looking for the gradients and not getting them.

**Comment by aswanthkrishna** [comment]
I am trying qaoa_example.py with the optimizer string set to mlpack. is it possible to get gradients using parameter shift/finite-difference?

**Comment by tnguyen-ornl** [comment]
Hi @aswanthkrishna,

A couple of suggestions:

1. Indeed, the problem that you are seeing is because the `mlpack` optimizer gave up after the first step since it didn't have the gradient. To be more precise, the default optimization method that `mlpack` will use is Adam (https://ensmallen.org/docs.html#adam) which is a gradient-based method.

XACC does give you an option to select a specific optimization method via the `mlpack-optimizer`   key, see https://xacc.readthedocs.io/en/latest/extensions.html#mlpack
For example, a gradient-free optimizer such as Simultaneous Perturbation Stochastic Approximation (SPSA) can get your QAOA optimization iteration going:
```
opt = xacc.getOptimizer('mlpack', { 
    'initial-parameters': initParams,
    'mlpack-optimizer': 'spsa'
})
```
It's worth noting that it may or may not give the same stepping quality as Cobyla (the default of `nlopt`) 
 
2. The QAOA algorithm can also evaluate the energy value at a specific set of parameters. Hence, you can also implement your own numerical parameter-shift/finite-difference strategy. For example, you can do something like this:
```
for i in range(maxIters):
    params = updateParams(...) # Define your stepping strategy here 
    # Evaluate the energy
    energy = qaoa.execute(buffer, params)
    # Cache energy value, new params, calculate gradients, etc.
    # or feed this (params, energy) pair to your optimizer of choice.
```

3. Lastly, built-in support for QAOA gradients in XACC is coming soon, so stay tuned. 

I hope that it helps.

**Comment by danclaudino** [comment]
QAOA now supports computation of gradients with parameter shift. The example in python/examples/qaoa_example.py illustrates how to use it.

**Comment by aswanthkrishna** [comment]
Great! thank you @danclaudino  @tnguyen-ornl  @amccaskey
