### ISSUE TITLE
xacc install fails on Ubuntu 16.04 running in Virtual Box

### ISSUE THREAD

**Issue by pdreher** [eclipse/xacc#33]
This xacc install was attempted on an Ubuntu 16.04 running in Virtual Box.  The following commands were used

Then I typed sudo make install and the whole thing crashed and burned

 This xacc install was attempted on an Ubuntu 16.04 running in Virtual Box.  The following commands were used 

[commands from attempted xacc install on Ubuntu 16-04.docx](https://github.com/eclipse/xacc/files/2028314/commands.from.attempted.xacc.install.on.Ubuntu.16-04.docx)

**Comment by amccaskey** [comment]
Hey Patrick, 

Will you please delete the contents of your build directory, re-run your CMake command, and copy the output here? Also instead of 
```bash
make install
```
will you instead run 
```bash
make install VERBOSE=1
```
and copy the output of that here as well?

I should note that in a new Ubuntu 16.04 Docker container I was able to run 
```bash
apt-get -y update
apt-get -y install gcc g++ libssl-dev libpython3-dev python3 cmake git
git clone --recursive https://github.com/eclipse/xacc
cd xacc && mkdir build && cd build
cmake .. -DPYTHON_INCLUDE_DIR=$(python3 -c "import sysconfig; print(sysconfig.get_paths()['platinclude'])")
make -j4 install
```
successfully. So I'm wondering if another compiler got picked up somehow. The output of those commands should be able to tell us what happened. 

Also note that I forgot to tell you to install python3 (in addition to libpython3-dev)

**Comment by amccaskey** [comment]
Can confirm that 
```bash
apt-get install clang-3.8
``` 
instead of gcc g++ works on fresh ubuntu 16.04 docker image. Requires
```bash
CXX=clang++-3.8 cmake ..
```

**Comment by pdreher** [comment]
Alex,

 

OK - got your messages.  I will do the steps you suggest and let you know.  However, it may be a day or so before I can get back to this.  I will be having knee surgery tomorrow morning to hopefully alleviate the difficulties that I have been having getting around for the last year or so.  It may be a day or so before I can get back to do the steps you suggest.  Speak to you soon.

 

Regards,

 

Patrick
