### ISSUE TITLE
Gradient tests failing when moving operator()() call outside the loop over measured circuits in VQE

### ISSUE THREAD

**Issue by danclaudino** [eclipse/xacc#368]
AutodiffTester and QuantumNaturalGradientTester fail when `operator()()` is called only once prior to the loop over measured circuits (https://github.com/danclaudino/xacc/blob/vqe_composite_operator/quantum/plugins/algorithms/vqe/vqe.cpp#L113).

@tnguyen-ornl

**Comment by tnguyen-ornl** [comment]
The reason is that the `PauliOperator` reverses the list of params when it is observing a kernel with variables.

See: https://github.com/eclipse/xacc/blob/master/quantum/observable/pauli/PauliOperator.cpp#L215
(inserting at 0 will reverse the list)

Looks like we're traditionally only doing `observe()` **then** `operator()()`, hence everything is consistent.
Now, when doing `operator()()` **before** `observe()`, the list of double is actually mapped in reverse order.

**Comment by tnguyen-ornl** [comment]
The reason is that the `PauliOperator` reverses the list of params when it is observing a kernel with variables.

See: https://github.com/eclipse/xacc/blob/master/quantum/observable/pauli/PauliOperator.cpp#L215
(inserting at 0 will reverse the list)

Looks like we're traditionally only doing `observe()` **then** `operator()()`, hence everything is consistent.
Now, when doing `operator()()` **before** `observe()`, the list of double is actually mapped in reverse
